// packages/addressr-vue/src/LocalityAutocomplete.vue
<!--
  @jtbd JTBD-003 (developer-integration) + JTBD-102 (end-user)
  Slots: item, loading, no-results, error
-->
<script setup lang="ts">
import { ref, computed } from 'vue';
import type { LocalitySearchResult } from '@mountainpass/addressr-core';
import { useLocalitySearch } from './useLocalitySearch';

const props = withDefaults(defineProps<{
  apiKey?: string;
  apiUrl?: string;
  apiHost?: string;
  label?: string;
  placeholder?: string;
  name?: string;
  required?: boolean;
  debounceMs?: number;
  fetchImpl?: typeof fetch;
}>(), {
  label: 'Search Australian suburbs and towns',
  placeholder: 'Start typing a suburb or town...',
  name: 'locality',
  required: false,
});

const emit = defineEmits<{
  select: [result: LocalitySearchResult];
}>();

const uid = `addressr-${Math.random().toString(36).slice(2, 9)}`;
const inputId = `${uid}-input`;
const listboxId = `${uid}-listbox`;
const statusId = `${uid}-status`;
const errorId = `${uid}-error`;

const search = useLocalitySearch({
  apiKey: props.apiKey,
  apiUrl: props.apiUrl,
  apiHost: props.apiHost,
  debounceMs: props.debounceMs,
  fetchImpl: props.fetchImpl,
});

const isOpen = ref(false);
const highlightedIndex = ref(-1);

function handleInput(event: Event) {
  const value = (event.target as HTMLInputElement).value;
  search.setQuery(value);
  isOpen.value = true;
  highlightedIndex.value = -1;
}

function handleKeydown(event: KeyboardEvent) {
  if (!isOpen.value && event.key === 'ArrowDown') {
    isOpen.value = true;
    return;
  }
  if (event.key === 'ArrowDown') {
    event.preventDefault();
    highlightedIndex.value = Math.min(highlightedIndex.value + 1, search.results.value.length - 1);
    if (highlightedIndex.value === search.results.value.length - 1 && search.hasMore.value) {
      search.loadMore();
    }
  } else if (event.key === 'ArrowUp') {
    event.preventDefault();
    highlightedIndex.value = Math.max(highlightedIndex.value - 1, -1);
  } else if (event.key === 'Enter' && highlightedIndex.value >= 0) {
    event.preventDefault();
    selectItem(highlightedIndex.value);
  } else if (event.key === 'Escape') {
    isOpen.value = false;
    highlightedIndex.value = -1;
  }
}

function selectItem(index: number) {
  const item = search.results.value[index];
  if (item) {
    emit('select', item);
    search.setQuery(`${item.name} ${item.state.abbreviation} ${item.postcode}`);
    isOpen.value = false;
    highlightedIndex.value = -1;
  }
}

function handleScroll(event: Event) {
  if (!search.hasMore.value || search.isLoadingMore.value) return;
  const el = event.target as HTMLElement;
  if (el.scrollHeight - el.scrollTop - el.clientHeight < 50) {
    search.loadMore();
  }
}

function handleBlur() {
  setTimeout(() => { isOpen.value = false; highlightedIndex.value = -1; }, 200);
}

const showMenu = computed(() =>
  isOpen.value && (
    search.results.value.length > 0 ||
    search.isLoading.value ||
    (search.query.value.length >= 3 && !search.isLoading.value)
  )
);

const activeDescendant = computed(() =>
  highlightedIndex.value >= 0 ? `${uid}-option-${highlightedIndex.value}` : undefined
);
</script>

<template>
  <div class="addressr-wrapper">
    <label :for="inputId" class="addressr-label">{{ props.label }}</label>
    <input
      :id="inputId"
      type="text"
      role="combobox"
      autocomplete="off"
      aria-autocomplete="list"
      aria-haspopup="listbox"
      :aria-expanded="showMenu"
      :aria-controls="listboxId"
      :aria-activedescendant="activeDescendant"
      :aria-describedby="search.error.value ? errorId : undefined"
      :aria-required="props.required || undefined"
      :aria-invalid="search.error.value ? true : undefined"
      :name="props.name"
      :placeholder="props.placeholder"
      :value="search.query.value"
      class="addressr-input"
      @input="handleInput"
      @keydown="handleKeydown"
      @blur="handleBlur"
      @focus="search.results.value.length > 0 && (isOpen = true)"
    />

    <div :id="statusId" role="status" aria-live="polite" aria-atomic="true" class="addressr-sr-only">
      <template v-if="search.isLoading.value">Searching suburbs and towns...</template>
      <template v-else-if="search.results.value.length > 0">{{ search.results.value.length }} suburbs and towns found</template>
      <template v-else-if="search.query.value.length >= 3">No suburbs or towns found</template>
    </div>

    <ul
      :id="listboxId"
      role="listbox"
      class="addressr-menu"
      :class="{ 'addressr-menu-hidden': !showMenu }"
      @scroll="handleScroll"
    >
      <template v-if="showMenu">
        <template v-if="search.isLoading.value">
          <slot name="loading">
            <li class="addressr-skeleton" style="width: 60%" aria-hidden="true"></li>
            <li class="addressr-skeleton" style="width: 70%" aria-hidden="true"></li>
            <li class="addressr-skeleton" style="width: 55%" aria-hidden="true"></li>
          </slot>
        </template>
        <template v-if="!search.isLoading.value && search.results.value.length === 0 && search.query.value.length >= 3">
          <slot name="no-results">
            <li class="addressr-no-results">No suburbs or towns found</li>
          </slot>
        </template>
        <li
          v-for="(item, index) in search.results.value"
          :key="item.pid"
          :id="`${uid}-option-${index}`"
          role="option"
          tabindex="-1"
          :aria-selected="highlightedIndex === index"
          class="addressr-item"
          :class="{ 'addressr-item-highlighted': highlightedIndex === index }"
          @click="selectItem(index)"
          @mouseenter="highlightedIndex = index"
        >
          <slot name="item" :item="item" :highlighted="highlightedIndex === index">
            <span>
              <strong>{{ item.name }}</strong> {{ item.state.abbreviation }} {{ item.postcode }}
            </span>
          </slot>
        </li>
        <li v-if="search.isLoadingMore.value" role="presentation" class="addressr-loading">Loading more...</li>
      </template>
    </ul>

    <template v-if="search.error.value">
      <slot name="error" :error="search.error.value">
        <div :id="errorId" class="addressr-error" role="alert" aria-live="assertive" aria-atomic="true">
          {{ search.error.value.message }}
        </div>
      </slot>
    </template>
  </div>
</template>

<style scoped>
.addressr-wrapper {
  position: relative;
  font-family: var(--addressr-font-family, system-ui, -apple-system, sans-serif);
}
.addressr-label {
  display: block;
  margin-bottom: 0.25rem;
  font-weight: 500;
  font-size: 0.875rem;
}
.addressr-input {
  width: 100%;
  padding: var(--addressr-padding-y, 0.625rem) var(--addressr-padding-x, 0.75rem);
  font-size: 1rem;
  line-height: 1.5;
  color: var(--addressr-text-color, inherit);
  border: 1px solid var(--addressr-border-color, #767676);
  border-radius: var(--addressr-border-radius, 0.25rem);
  box-sizing: border-box;
}
.addressr-input:focus-visible {
  outline: 2px solid var(--addressr-focus-color, #005fcc);
  outline-offset: 1px;
  border-color: var(--addressr-focus-color, #005fcc);
}
.addressr-menu {
  position: absolute;
  z-index: var(--addressr-z-index, 1000);
  width: 100%;
  max-height: 20rem;
  overflow-y: auto;
  margin: 0;
  padding: 0;
  list-style: none;
  background: var(--addressr-bg, #fff);
  border: 1px solid var(--addressr-border-color, #767676);
  border-top: none;
  border-radius: 0 0 var(--addressr-border-radius, 0.25rem) var(--addressr-border-radius, 0.25rem);
  box-shadow: var(--addressr-shadow, 0 4px 6px rgba(0, 0, 0, 0.1));
  box-sizing: border-box;
}
.addressr-menu-hidden { display: none; }
.addressr-item {
  min-height: 2.75rem;
  padding: var(--addressr-padding-y, 0.625rem) var(--addressr-padding-x, 0.75rem);
  cursor: pointer;
  display: flex;
  align-items: center;
  font-size: 0.9375rem;
  line-height: 1.4;
}
.addressr-item-highlighted {
  background-color: var(--addressr-highlight-bg, #e8f0fe);
}
.addressr-no-results {
  padding: var(--addressr-padding-y, 0.625rem) var(--addressr-padding-x, 0.75rem);
  color: var(--addressr-muted-color, #555);
  font-style: italic;
  font-size: 0.875rem;
}
.addressr-loading {
  padding: var(--addressr-padding-y, 0.625rem) var(--addressr-padding-x, 0.75rem);
  color: var(--addressr-muted-color, #555);
  font-size: 0.875rem;
}
.addressr-error {
  padding: var(--addressr-padding-y, 0.625rem) var(--addressr-padding-x, 0.75rem);
  color: var(--addressr-error-color, #d32f2f);
  font-size: 0.875rem;
}
.addressr-skeleton {
  height: 1rem;
  margin: var(--addressr-padding-y, 0.625rem) var(--addressr-padding-x, 0.75rem);
  border-radius: var(--addressr-border-radius, 0.25rem);
  background: linear-gradient(
    90deg,
    var(--addressr-skeleton-from, #e0e0e0) 25%,
    var(--addressr-skeleton-to, #f0f0f0) 50%,
    var(--addressr-skeleton-from, #e0e0e0) 75%
  );
  background-size: 200% 100%;
  animation: addressr-shimmer 1.5s infinite linear;
}
@keyframes addressr-shimmer {
  0% { background-position: 200% 0; }
  100% { background-position: -200% 0; }
}
@media (prefers-reduced-motion: reduce) {
  .addressr-skeleton { animation: none; }
}
.addressr-sr-only {
  position: absolute;
  width: 1px;
  height: 1px;
  padding: 0;
  margin: -1px;
  overflow: hidden;
  clip: rect(0, 0, 0, 0);
  white-space: nowrap;
  border: 0;
}
</style>

// packages/addressr-react/src/components/LocalityAutocomplete.tsx
// @jtbd JTBD-003 (developer-integration) + JTBD-102 (end-user)
import { useId, useRef, useCallback } from 'react';
import { useCombobox } from 'downshift';
import { useLocalitySearch } from '../hooks/useLocalitySearch';
import type { LocalitySearchResult } from '@mountainpass/addressr-core';
import styles from './AddressAutocomplete.module.css';

export interface LocalityAutocompleteProps {
  /** RapidAPI key. Omit when connecting directly to an addressr instance. */
  apiKey?: string;
  onSelect: (result: LocalitySearchResult) => void;
  label?: string;
  placeholder?: string;
  className?: string;
  /** Input name attribute for form submission. */
  name?: string;
  /** Whether the field is required. Sets aria-required. */
  required?: boolean;
  debounceMs?: number;
  apiUrl?: string;
  apiHost?: string;
  /**
   * Custom loading state renderer. When provided, you are responsible for
   * accessibility — return `<li>` elements with appropriate roles.
   */
  renderLoading?: () => React.ReactNode;
  /**
   * Custom no-results renderer. When provided, you are responsible for
   * accessibility — return `<li>` elements.
   */
  renderNoResults?: () => React.ReactNode;
  /**
   * Custom error renderer. When provided, you are responsible for
   * accessibility — include `role="alert"` on the container.
   */
  renderError?: (error: Error) => React.ReactNode;
  /**
   * Custom result item renderer. Content is wrapped in the existing `<li>`
   * with ARIA attributes.
   */
  renderItem?: (item: LocalitySearchResult, highlighted: boolean) => React.ReactNode;
  /** @internal */
  fetchImpl?: typeof fetch;
}

export function LocalityAutocomplete({
  apiKey,
  onSelect,
  label = 'Search Australian suburbs and towns',
  placeholder = 'Start typing a suburb or town...',
  className,
  name = 'locality',
  required,
  debounceMs,
  apiUrl,
  apiHost,
  renderLoading,
  renderNoResults,
  renderError,
  renderItem,
  fetchImpl,
}: LocalityAutocompleteProps) {
  const id = useId();
  const errorId = `${id}-error`;
  const statusId = `${id}-status`;
  const onSelectRef = useRef(onSelect);
  onSelectRef.current = onSelect;

  const { query, setQuery, results, isLoading, isLoadingMore, hasMore, loadMore, error } = useLocalitySearch({
    apiKey,
    apiUrl,
    apiHost,
    debounceMs,
    fetchImpl,
  });

  const { isOpen, getLabelProps, getMenuProps, getInputProps, highlightedIndex, getItemProps } =
    useCombobox<LocalitySearchResult>({
      items: results,
      inputValue: query,
      onInputValueChange: ({ inputValue }) => setQuery(inputValue ?? ''),
      onSelectedItemChange: ({ selectedItem }) => {
        if (selectedItem) {
          onSelectRef.current(selectedItem);
        }
      },
      itemToString: (item) => (item ? `${item.name} ${item.state.abbreviation} ${item.postcode}` : ''),
    });

  const handleMenuScroll = useCallback(
    (event: React.UIEvent<HTMLUListElement>) => {
      if (!hasMore || isLoadingMore) return;
      const { scrollTop, scrollHeight, clientHeight } = event.currentTarget;
      if (scrollHeight - scrollTop - clientHeight < 50) {
        loadMore();
      }
    },
    [hasMore, isLoadingMore, loadMore],
  );

  const showMenu = isOpen && results.length > 0;
  const showLoading = isOpen && isLoading && results.length === 0;
  const showNoResults = isOpen && !isLoading && results.length === 0 && query.length >= 3;

  return (
    <div className={`${styles.wrapper} ${className ?? ''}`}>
      <label {...getLabelProps()} className={styles.label}>
        {label}
      </label>
      <input
        {...getInputProps({
          autoComplete: 'off',
          placeholder,
          name,
          'aria-expanded': showMenu,
          'aria-describedby': error ? errorId : undefined,
          'aria-required': required || undefined,
          'aria-invalid': error ? true : undefined,
        })}
        className={styles.input}
      />

      <div id={statusId} role="status" aria-live="polite" aria-atomic="true" className={styles.srOnly}>
        {isLoading && 'Searching suburbs and towns...'}
        {!isLoading &&
          results.length > 0 &&
          (results.length === 1 ? '1 suburb or town found' : `${results.length} suburbs and towns found`)}
        {!isLoading && results.length === 0 && query.length >= 3 && 'No suburbs or towns found'}
      </div>

      <ul
        {...getMenuProps({ onScroll: handleMenuScroll })}
        hidden={!showMenu}
        className={`${styles.menu} ${!showMenu ? styles.menuHidden : ''}`}
      >
        {showMenu && (
          <>
            {results.map((item, index) => (
              <li
                key={item.pid}
                {...getItemProps({ item, index })}
                className={`${styles.item} ${highlightedIndex === index ? styles.itemHighlighted : ''}`}
              >
                {renderItem ? (
                  renderItem(item, highlightedIndex === index)
                ) : (
                  <span>
                    <strong>{item.name}</strong> {item.state.abbreviation} {item.postcode}
                  </span>
                )}
              </li>
            ))}
            {isLoadingMore && (
              <li role="presentation" className={styles.loading}>
                Loading more...
              </li>
            )}
          </>
        )}
      </ul>

      {(showLoading || showNoResults) && (
        <ul className={styles.menu} aria-hidden="true">
          {showLoading &&
            (renderLoading ? (
              renderLoading()
            ) : (
              <>
                <li className={styles.skeleton} style={{ width: '60%' }} />
                <li className={styles.skeleton} style={{ width: '70%' }} />
                <li className={styles.skeleton} style={{ width: '55%' }} />
              </>
            ))}
          {showNoResults &&
            (renderNoResults ? renderNoResults() : <li className={styles.noResults}>No suburbs or towns found</li>)}
        </ul>
      )}

      {error &&
        (renderError ? (
          renderError(error)
        ) : (
          <div id={errorId} className={styles.error} role="alert">
            {error.message}
          </div>
        ))}
    </div>
  );
}
